version: "3.9"

services:
  nginx:
    image: nginx:1.23
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - static_images:/etc/public/images
    container_name: caps_pizza_nginx
    depends_on:
      - web
      - api

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    container_name: caps_pizza_db
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: dockerfile.api.prod
      args:
        WORKDIR: /usr/src/caps-pizza/api
    environment:
      - SECRET=${API_SECRET}
      - PORT=8080
      - HOST=127.0.0.1
      - FRONTEND_URL=http://${HOST}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - DATABASE_HOST=caps_pizza_db
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=5432
      - SYNC_ON=1
    depends_on:
      - db
    volumes:
      - static_images:/usr/src/caps-pizza/api/packages/api/static/images
    container_name: caps_pizza_api
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./dockerfile.web.prod
      args:
        WORKDIR: /usr/src/caps-pizza/web
        PORT: 3000
        HOST: "127.0.0.1"
        IMAGE_HOST: ${HOST}
        NEXT_PUBLIC_API_URL: "http://${HOST}/api/v1"
        NEXT_PUBLIC_IMAGES_SOURCE_URL: "http://${HOST}/api/v1"
    depends_on:
      - api
    container_name: caps_pizza_web
    restart: unless-stopped

volumes:
  postgres:
  static_images:
