FROM node:18.8-alpine3.15 as builder

# Args
ARG WORKDIR

# Env
ENV NODE_ENV=test

WORKDIR ${WORKDIR}

COPY lerna.json .

COPY package.json .
COPY yarn.lock .

COPY packages/common/package.json ./packages/common/package.json
COPY packages/api/package.json ./packages/api/package.json

# Install dev deps
RUN yarn install
RUN yarn bootstrap

# Copy project
COPY packages/common ./packages/common
COPY packages/api ./packages/api

# Build common package
RUN yarn build:common

RUN yarn pkg:link

# Run linter
RUN yarn lint:api

# Run formatter
RUN yarn fmt:check:api

CMD yarn start:test:cov:api  
