# Builder
FROM node:18.8-alpine3.15 as builder

# Args
ARG WORKDIR
ARG PORT=3000
ARG HOST=127.0.0.1
ARG IMAGE_HOST=127.0.0.1
ARG API_URL=api_url_placeholder
ARG IMAGES_SOURCE_URL=image_source_url_placeholder

# Env
ENV NODE_ENV=test
ENV HOST=${HOST}
ENV PORT=${PORT}
ENV IMAGE_HOST=${IMAGE_HOST}
ENV API_URL=${API_URL}
ENV IMAGES_SOURCE_URL=${IMAGES_SOURCE_URL}

# Init
WORKDIR ${WORKDIR}

COPY lerna.json .

COPY package.json .
COPY yarn.lock .

COPY packages/common/package.json ./packages/common/package.json
COPY packages/web/package.json ./packages/web/package.json

RUN yarn install
RUN yarn bootstrap

# Copy project
COPY packages/common ./packages/common
COPY packages/web ./packages/web

# Build common package
RUN yarn build:common

RUN yarn pkg:link

# Run linter
RUN yarn lint:web

# # Run formatter
# RUN yarn fmt:web

CMD yarn start:test:cov:web
