version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    container_name: caps_pizza_test_db
    restart: "no"

  api:
    build:
      context: .
      dockerfile: dockerfile.api.test
      args:
        WORKDIR: /usr/src/caps-pizza/api
    environment:
      - PORT=8080
      - HOST=127.0.0.1
      - SECRET=${API_SECRET}
      - FRONTEND_URL=http://${HOST}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - DATABASE_HOST=caps_pizza_test_db
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=5432
      - SYNC_ON=1
    depends_on:
      - db
    volumes:
      - ./packages/api/coverage:/usr/src/caps-pizza/api/packages/api/coverage
    container_name: caps_pizza_test_api
    restart: "no"

  web:
    build:
      context: .
      dockerfile: ./dockerfile.web.test
      args:
        WORKDIR: /usr/src/caps-pizza/web
    environment:
      - HOST=3000
      - PORT=127.0.0.1
      - IMAGE_HOST=${HOST}
      - API_URL=http://${HOST}/api/v1
      - IMAGES_SOURCE_URL=http://${HOST}/api/v1
    depends_on:
      - api
    volumes:
      - ./packages/web/coverage:/usr/src/caps-pizza/web/packages/web/coverage
    container_name: caps_pizza_test_web
    restart: "no"
