# Builder
FROM node:18.8-alpine3.15 as builder

# Args
ARG WORKDIR
ARG PORT=3000
ARG HOST=127.0.0.1
ARG IMAGE_HOST=127.0.0.1
ARG NEXT_PUBLIC_API_URL=api_url_placeholder
ARG NEXT_PUBLIC_IMAGES_SOURCE_URL=image_source_url_placeholder

# Env
ENV NODE_ENV=test
ENV HOST=${HOST}
ENV PORT=${PORT}
ENV IMAGE_HOST=${IMAGE_HOST}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_IMAGES_SOURCE_URL=${NEXT_PUBLIC_IMAGES_SOURCE_URL}

# Init
WORKDIR ${WORKDIR}

COPY lerna.json .

COPY package.json .
COPY yarn.lock .

COPY packages/common/package.json ./packages/common/package.json

COPY packages/web/package.json ./packages/web/package.json

RUN printf "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL\nNEXT_PUBLIC_IMAGES_SOURCE_URL=$NEXT_PUBLIC_IMAGES_SOURCE_URL" >> ./packages/web/.env.production

RUN yarn install
RUN npx lerna bootstrap

# Copy project
COPY . .

# Build common package
RUN npx lerna run build --scope @monorepo/common

CMD npx lerna link && npx lerna run start:test --scope @monorepo/web
