name: Deploy CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push API package
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile.api.prod
          push: true
          build-args: |
            WORKDIR=/usr/src/caps-pizza/api
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/caps-pizza-api:latest

      - name: Build and push WEB package
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile.web.prod
          push: true
          build-args: |
            WORKDIR=/usr/src/caps-pizza/web
            PORT=3000
            HOST=127.0.0.1
            IMAGE_HOST=${{ secrets.HOST }}
            NEXT_PUBLIC_API_URL=http://${{ secrets.HOST }}/api/v1
            NEXT_PUBLIC_IMAGES_SOURCE_URL=http://${{ secrets.HOST }}/api/v1
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/caps-pizza-web:latest
