name: Test CI
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
env:
  HOST: ${{secrets.HOST}}
  API_SECRET: ${{secrets.API_SECRET}}
  JWT_ACCESS_TOKEN_SECRET: ${{secrets.JWT_ACCESS_TOKEN_SECRET}}
  JWT_REFRESH_TOKEN_SECRET: ${{secrets.JWT_REFRESH_TOKEN_SECRET}}
  DATABASE_NAME: ${{secrets.DATABASE_NAME}}
  DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
  DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Run API tests
        run: docker compose --file docker-compose.test.yml up --build --abort-on-container-exit api

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: ./packages/api
          path-to-lcov: ./packages/api/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-web:
    needs: test-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Run API tests
        run: docker compose --file docker-compose.test.yml up --build --abort-on-container-exit web

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: ./packages/web
          path-to-lcov: ./packages/web/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
